export const languageCodeMapper = new Map<string, string>([
    ['en', 'English'],
    ['es', 'Spanish'],
    ['fr', 'French'],
    ['de', 'German'],
    ['it', 'Italian'],
    ['pt', 'Portuguese'],
    ['zh', 'Chinese'],
    ['ja', 'Japanese'],
    ['ru', 'Russian'],
    ['ar', 'Arabic'],
    ['hi', 'Hindi'],
    ['bn', 'Bengali'],
    ['sv', 'Swedish'],
    ['nl', 'Dutch'],
    ['ko', 'Korean'],
    ['ta', 'Tamil'],
    ['te', 'Telugu'],
    ['ml', 'Malayalam'],
    ['gu', 'Gujarati'],
    ['pa', 'Punjabi'],
    ['mr', 'Marathi'],
    ['ur', 'Urdu'],
    ['kn', 'Kannada'],
    ['ig', 'Igbo'],
    ['ha', 'Hausa'],
    ['sw', 'Swahili'],
    ['yo', 'Yoruba'],
]);

