---
name: PROD-CI-CD
on:
  push:
    branches:
      - main
jobs:
  Deploy-ECS:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: New Release Publish
        uses: release-drafter/release-drafter@v5
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
